#!/bin/bash
# Install VAS and Join AD in the correct location
# Global
working_dir=$(basename $(cd $(dirname $0) && pwd))
containing_dir=$(cd $(dirname $0)/.. && pwd)
basename="${containing_dir}/${working_dir}"
os_name=`uname -s`
#

# VAS join info
ad_domain="strategic.ad"
ad_dn="dc=strategic,dc=ad"
unix_ou="ou=unix,dc=strategic,dc=ad"
joiner_keytab="$basename/files/joiner.keytab"
VAStool="/opt/quest/bin/vastool"
joiner="centos7a-joiner@STRATEGIC.AD"
#PolicySvr="centos7a.strategic.ad"
PolicySvr="PMsudo"

checkRoot() {
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi }

set_ou(){
case $os_name in
  "Linux")
    ou_name="linux"
    ou_final="ou=${ou_name},${unix_ou}"
  ;;

  "SunOS")
    ou_name="solaris"
    ou_final="ou=${ou_name},${unix_ou}"
  ;;

  "AIX")
    ou_name="aix"
    ou_final="ou=${ou_name},${unix_ou}"
  ;;

  "HP-UX")
    ou_name="hpux"
    ou_final="ou=${ou_name},${unix_ou}"
  ;;

  *)
    echo $"OS unsupported by this script, Linux, SunOS, AIX, HP-UX only"
  exit 1
esac

}
installVAS() {
if [ ! -x $VAStool ]; then
$basename/install.sh -qa vasclnt vasgp
fi
}

joinVASagent() {
# Join adding to the Unix OU
#$VAStool -u  $joiner -w $pass join -f -c $unix_ou $ad_domain
# Join to the OS based OU
$VAStool -u $joiner -k $joiner_keytab join -f -c "$ou_final" $ad_domain
}

installPlugin() {
# Install the policy plugin
if [ ! -x /opt/quest/sbin/pmjoin_plugin ];then
  Machine=`uname -m`
  if [ "$os_name" = "Linux" ] && [ "$Machine" = "x86_64" ]; then
    rpm -i $basename/sudo_plugin/linux-x86_64/qpm-plugin-*.rpm
  elif [ "$os_name" = "Linux" ] && [ "$Machine" = "x86" ]; then
    rpm -i $basename/sudo_plugin/linux-intel/qpm-plugin-*.rpm
  elif [ "$os_name" = "AIX" ]; then
    # Install AIX Package
    installp -ac -d qpm-plugin*.bff all
  elif [ "$os_name" = "Solaris" ]; then
    # pkgadd -d
    echo "Solaris"
  else 
    echo "Unsupported Platform"
  fi
fi
}

joinPlugin() {
  # Joins the plugin to the Policy group for keystroke logging only
  echo "Test1234" | /opt/quest/sbin/pmjoin_plugin -q -b -o -a $PolicySvr
  # Joins plugin with centralized policy and keystroke logging
#  echo "Test1234" | /opt/quest/sbin/pmjoin_plugin -q -b -a $PolicySvr
  if [ -f "/etc/sudoers" ] ; then
    echo "Defaults log_output" >> /etc/sudoers
  else
    echo "/etc/sudoers NOT FOUND, Manually add \"Defaults log_output\" to the sudoers file"
  fi 
}

configUserMap() {
cp $UserMap /etc/usermap
$VAStool configure vas vas_auth user-map-files /etc/usermap
}

checkRoot
set_ou
#echo "OU set to: ${ou_final}"
installVAS
joinVASagent
configUserMap
installPlugin
joinPlugin
